steps:
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: setup_ssh
  entrypoint: bash
  secretEnv: ["SSH_KEY"]
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: "ssh"
    path: /root/.ssh

- name: python
  id: run_main_script
  entrypoint: bash
  dir: gcloud/preload_instruments
  args:
  - -c
  - |
    ls -ltr
    pip install git+ssh://git@github.com/senderr/crypto-mart.git
    python3 main.py
  volumes:
  - name: "ssh"
    path: /root/.ssh

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: push_to_gcs
  entrypoint: bash
  dir: gcloud/preload_instruments
  args:
  - -c
  - |
    tar czf cache.tar.gz cache
    gsutil cp cache.tar.gz gs://crypto-arb-resources/artifacts/spreads-arb/

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-ssh-pkey/versions/latest
    env: "SSH_KEY"

timeout: 2400s